import { type NextPage } from "next";
import Head from "next/head";
import { useState } from "react";
import { Call } from "../components/Call";
import { Settings } from "../components/Settings";
import { Container, Group, Stack } from "@mantine/core";
import { CallProvider } from "../components/CallProvider";

const Home: NextPage = () => {
  const [settingsA, setSettingsA] = useState<Settings | null>(null);
  const [settingsB, setSettingsB] = useState<Settings | null>(null);

  return (
    <>
      <Head>
        <title>100ms vanilla library</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Stack>
            <Group>
              <Settings
                onChange={(settings) => setSettingsA(settings)}
                value={{
                  token: process.env.NEXT_PUBLIC_RED_TOKEN,
                }}
              />
              <CallProvider>
                {settingsA ? <Call {...settingsA} roomName="Red" /> : null}
              </CallProvider>
            </Group>
            <Stack>
              <Group>
                <Settings
                  onChange={(settings) => setSettingsB(settings)}
                  value={{
                    token: process.env.NEXT_PUBLIC_BLUE_TOKEN,
                  }}
                />
                <CallProvider>
                  {settingsB ? <Call {...settingsB} roomName="Blue" /> : null}
                </CallProvider>
              </Group>
            </Stack>
          </Stack>
        </Container>
      </main>
    </>
  );
};

export default Home;
