import { type NextPage } from "next";
import Head from "next/head";
import { useMemo, useState } from "react";
import type { HMSStore } from "@100mslive/react-sdk";
import { HMSReactiveStore, HMSRoomProvider } from "@100mslive/react-sdk";
import { Call } from "../components/Call";
import { Settings } from "../components/Settings";
import { Container, Group, Stack } from "@mantine/core";
import create from "zustand";

const Home: NextPage = () => {
  const [settingsA, setSettingsA] = useState<Settings | null>(null);
  const [settingsB, setSettingsB] = useState<Settings | null>(null);
  const storeA = useMemo(() => {
    const store = new HMSReactiveStore();
    return {
      actions: store.getActions(),
      notifications: store.getNotifications(),
      store: create<HMSStore>({
        ...store.getStore(),
        setState: () => {
          throw new Error("Store not ready");
        },
        destroy: () => {
          throw new Error("Store not ready");
        },
      }),
    };
  }, []);
  const storeB = useMemo(() => {
    const store = new HMSReactiveStore();
    return {
      actions: store.getActions(),
      notifications: store.getNotifications(),
      store: create<HMSStore>({
        ...store.getStore(),
        setState: () => {
          throw new Error("Store not ready");
        },
        destroy: () => {
          throw new Error("Store not ready");
        },
      }),
    };
  }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Container>
          <Stack>
            <Group>
              <Settings
                onChange={(settings) => setSettingsA(settings)}
                value={{
                  token: process.env.NEXT_PUBLIC_RED_TOKEN,
                }}
              />
              <HMSRoomProvider {...storeA}>
                {settingsA ? <Call {...settingsA} roomName="Red" /> : null}
              </HMSRoomProvider>
            </Group>
            <Stack>
              <Group>
                <Settings
                  onChange={(settings) => setSettingsB(settings)}
                  value={{
                    token: process.env.NEXT_PUBLIC_BLUE_TOKEN,
                  }}
                />
                <HMSRoomProvider {...storeB}>
                  {settingsB ? <Call {...settingsB} roomName="Blue" /> : null}
                </HMSRoomProvider>
              </Group>
            </Stack>
          </Stack>
        </Container>
      </main>
    </>
  );
};

export default Home;
